okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB