-- CREATE NEW TABLE FOR EXTRA CLASS DETAILS (NOT IN API)

CREATE TABLE class_extra_details (
    id bigserial PRIMARY KEY,
    class_index text,
    class_name text,
    class_tagline text,
    class_flavour text,
    class_description text,
    class_primary_ability text
);

INSERT INTO class_extra_details (id, class_index, class_name, class_tagline, class_flavour, class_description, class_primary_ability)
VALUES
    (1, 'barbarian', 'Barbarian', 'A Fierce Warrior of Primal Rage', 'Barbarians are mighty warriors who are powered by primal forces of the multiverse that manifest as a Rage.', 'Barbarians are mighty warriors who are powered by primal forces of the multiverse that manifest as a Rage. More than a mere emotion—and not limited to anger—this Rage is an incarnation of a predator’s ferocity, a storm’s fury, and a sea’s turmoil.

Some Barbarians personify their Rage as a fierce spirit or revered forebear. Others see it as a connection to the pain and anguish of the world, as an impersonal tangle of wild magic, or as an expression of their own deepest self. For every Barbarian, their Rage is a power that fuels not just battle prowess, but also uncanny reflexes and heightened senses.

Barbarians often serve as protectors and leaders in their communities. They charge headlong into danger so those under their protection don’t have to. Their courage in the face of danger makes Barbarians perfectly suited for adventure.', 'Strength'),
    (2, 'bard', 'Bard', 'An Inspiring Performer of Music, Dance, and Magic', 'Invoking magic through music, dance, and verse, Bards are expert at inspiring others, soothing hurts, disheartening foes, and creating illusions.', 'Invoking magic through music, dance, and verse, Bards are expert at inspiring others, soothing hurts, disheartening foes, and creating illusions. Bards believe the multiverse was spoken into existence and that remnants of its Words of Creation still resound and glimmer on every plane of existence. Bardic magic attempts to harness those words, which transcend any language.

Anything can inspire a new song or tale, so Bards are fascinated by almost everything. They become masters of many things, including performing music, working magic, and making jests.

A Bard’s life is spent traveling, gathering lore, telling stories, and living on the gratitude of audiences, much like any other entertainer. But Bards’ depth of knowledge and mastery of magic sets them apart.', 'Charisma'),
    (3, 'cleric', 'Cleric', 'A Miraculous Priest of Divine Power', 'Clerics can reach out to the divine magic of the Outer Planes and channel it to bolster people and battle foes.', 'Clerics draw power from the realms of the gods and harness it to work miracles. Blessed by a deity, a pantheon, or another immortal entity, a Cleric can reach out to the divine magic of the Outer Planes—where gods dwell—and channel it to bolster people and battle foes.

Because their power is a divine gift, Clerics typically associate themselves with temples dedicated to the deity or other immortal force that unlocked their magic. Harnessing divine magic doesn’t rely on specific training, yet Clerics might learn prayers and rites that help them draw on power from the Outer Planes.

Not every member of a temple or shrine is a Cleric. Some priests are called to a simple life of temple service, carrying out their devotion through prayer and rituals, not through magic. Many mortals claim to speak for the gods, but few can marshal the power of those gods the way a Cleric can.', 'Wisdom'),
    (4, 'druid', 'Druid', 'A Nature Priest of Primal Power', 'Druids call on the forces of nature, harnessing magic to heal, transform into animals, and wield elemental destruction.', 'Druids belong to ancient orders that call on the forces of nature. Harnessing the magic of animals, plants, and the four elements, Druids heal, transform into animals, and wield elemental destruction.

Revering nature above all, individual Druids gain their magic from nature, a nature deity, or both, and they typically unite with other Druids to perform rites that mark the passage of the seasons and other natural cycles.

Druids are concerned with the delicate ecological balance that sustains plant and animal life and with the need for people to live in harmony with nature. Druids often guard sacred sites or watch over regions of unspoiled nature, but when a significant danger arises, Druids take a more active role as adventurers who combat the threat.', 'Wisdom'),
    (5, 'fighter', 'Fighter', 'A Master of All Arms and Armor', 'Fighters all share an unparalleled prowess with weapons and armor, and are well acquainted with death, both meting it out and defying it.', 'Fighters rule many battlefields. Questing knights, royal champions, elite soldiers, and hardened mercenaries—as Fighters, they all share an unparalleled prowess with weapons and armor. And they are well acquainted with death, both meting it out and defying it.

Fighters master various weapon techniques, and a well-equipped Fighter always has the right tool at hand for any combat situation. Likewise, a Fighter is adept with every form of armor. Beyond that basic degree of familiarity, each Fighter specializes in certain styles of combat. Some concentrate on archery, some on fighting with two weapons at once, and some on augmenting their martial skills with magic. This combination of broad ability and extensive specialization makes Fighters superior combatants.', 'Strength or Dexterity'),
    (6, 'monk', 'Monk', 'A Martial Artist of Supernatural Focus', 'Monks focus their internal reservoirs of power to create extraordinary, even supernatural, effects.', 'Monks use rigorous combat training and mental discipline to align themselves with the multiverse and focus their internal reservoirs of power. Different Monks conceptualize this power in various ways: as breath, energy, life force, essence, or self, for example. Whether channeled as a striking display of martial prowess or as a subtler manifestation of defense and speed, this power infuses all that a Monk does.

Monks focus their internal power to create extraordinary, even supernatural, effects. They channel uncanny speed and strength into their attacks, with or without the use of weapons. In a Monk’s hands, even the most basic weapons can become sophisticated implements of combat mastery.

Many Monks find that a structured life of ascetic withdrawal helps them cultivate the physical and mental focus they need to harness their power. Other Monks believe that immersing themselves in the vibrant confusion of life helps to fuel their determination and discipline.

Monks generally view adventures as tests of their physical and mental development. They are driven by a desire to accomplish a greater mission than merely slaying monsters and plundering treasure; they strive to turn themselves into living weapons.', 'Dexterity and Wisdom'),
    (7, 'paladin', 'Paladin', 'A Devout Warrior of Sacred Oaths', 'Paladins live on the front lines of the cosmic struggle, united by their oaths against the forces of annihilation.', 'Paladins are united by their oaths to stand against the forces of annihilation and corruption. Whether sworn before a god’s altar, in a sacred glade before nature spirits, or in a moment of desperation and grief with the dead as the only witnesses, a Paladin’s oath is a powerful bond. It is a source of power that turns a devout warrior into a blessed champion.

Paladins train to learn the skills of combat, mastering a variety of weapons and armor. Even so, their martial skills are secondary to the magical power they wield: power to heal the injured, smite their foes, and protect the helpless and those who fight at their side.

Almost by definition, the life of a Paladin is an adventuring life, for every Paladin lives on the front lines of the cosmic struggle against annihilation. Fighters are rare enough among the ranks of a world’s armies, but even fewer people can claim the calling of a Paladin. When they do receive the call, these blessed folk turn from their former occupations and take up arms and magic.', 'Strength and Charisma'),
    (8, 'ranger', 'Ranger', 'A Wandering Warrior Imbued with Primal Magic', 'Rangers are honed with deadly focus and harness primal powers to protect the world from the ravages of monsters and tyrants.', 'Far from bustling cities, amid the trees of trackless forests and across wide plains, Rangers keep their unending watch in the wilderness. Rangers learn to track their quarry as a predator does, moving stealthily through the wilds and hiding themselves in brush and rubble.

Thanks to their connection with nature, Rangers can also cast spells that harness primal powers of the wilderness. A Ranger’s talents and magic are honed with deadly focus to protect the world from the ravages of monsters and tyrants.', 'Dexterity and Wisdom'),
    (9, 'rogue', 'Rogue', 'A Dexterous Expert in Stealth and Subterfuge', 'Rogues have a knack for finding the solution to just about any problem, prioritizing subtle strikes over brute strength.', 'Rogues rely on cunning, stealth, and their foes’ vulnerabilities to get the upper hand in any situation. They have a knack for finding the solution to just about any problem. A few even learn magical tricks to supplement their other abilities. Many Rogues focus on stealth and deception, while others refine skills that help them in a dungeon environment, such as climbing, finding and disarming traps, and opening locks.

In combat, Rogues prioritize subtle strikes over brute strength. They would rather make one precise strike than wear an opponent down with a barrage of blows.

Some Rogues began their careers as criminals, while others used their cunning to fight crime. Whatever a Rogue’s relation to the law, no common criminal or officer of the law can match the subtle brilliance of the greatest Rogues.', 'Dexterity'),
    (10, 'sorcerer', 'Sorcerer', 'A Dazzling Mage Filled with Innate Magic', 'Sorcerers harness and channel the raw, roiling power of innate magic that is stamped into their very being.', 'Sorcerers wield innate magic that is stamped into their being. Some Sorcerers can’t name the origin of their power, while others trace it to strange events in their personal or family history. The blessing of a dragon or a dryad at a baby’s birth or the strike of lightning from a clear sky might spark a Sorcerer’s gift. So too might the gift of a deity, exposure to the strange magic of another plane of existence, or a glimpse into the inner workings of reality. Whatever the origin, the result is an indelible mark on the Sorcerer, a churning magic that can be passed down through generations.

Sorcerers don’t learn magic; the raw, roiling power of magic is part of them. The essential art of a Sorcerer is learning to harness and channel that innate magic, allowing the Sorcerer to discover new and staggering ways to unleash their power. As Sorcerers master their innate magic, they grow more attuned to its origin, developing distinct powers that reflect its source.

Sorcerers are rare. Some family lines produce exactly one Sorcerer in every generation, but most of the time, the talents of sorcery appear as a fluke. People who have this magical power soon discover that it doesn’t like to stay quiet. A Sorcerer’s magic wants to be wielded.', 'Charisma'),
    (11, 'warlock', 'Warlock', 'An Occultist Empowered by Otherworldly Pacts', 'Warlocks quest for knowledge that lies hidden in the fabric of the multiverse, piecing together arcane secrets to bolster their own power.', 'Warlocks quest for knowledge that lies hidden in the fabric of the multiverse. They often begin their search for magical power by delving into tomes of forbidden lore, dabbling in invocations meant to attract the power of extraplanar beings, or seeking places of power where the influence of these beings can be felt. In no time, each Warlock is drawn into a binding pact with a powerful patron. Drawing on the ancient knowledge of beings such as angels, archfey, demons, devils, hags, and alien entities of the Far Realm, Warlocks piece together arcane secrets to bolster their own power.

Warlocks view their patrons as resources, as means to the end of achieving magical power. Some Warlocks respect, revere, or even love their patrons; some serve their patrons grudgingly; and some seek to undermine their patrons even as they wield the power their patrons have given them.

Once a pact is made, a Warlock’s thirst for knowledge and power can’t be slaked with mere study. Most Warlocks spend their days pursuing greater power and deeper knowledge, which typically means some kind of adventure.', 'Charisma'),
    (12, 'wizard', 'Wizard', 'A Scholarly Magic-User of Arcane Power', 'Wizards cast spells of explosive fire, arcing lightning, subtle deception, and spectacular transformations.', 'Wizards are defined by their exhaustive study of magic’s inner workings. They cast spells of explosive fire, arcing lightning, subtle deception, and spectacular transformations. Their magic conjures monsters from other planes of existence, glimpses the future, or forms protective barriers. Their mightiest spells change one substance into another, call meteors from the sky, or open portals to other worlds.

Most Wizards share a scholarly approach to magic. They examine the theoretical underpinnings of magic, particularly the categorization of spells into schools of magic. Renowned Wizards such as Bigby, Tasha, Mordenkainen, and Yolande have built on their studies to invent iconic spells now used across the multiverse.

The closest a Wizard is likely to come to an ordinary life is working as a sage or lecturer. Other Wizards sell their services as advisers, serve in military forces, or pursue lives of crime or domination.

But the lure of knowledge calls even the most unadventurous Wizards from the safety of their libraries and laboratories and into crumbling ruins and lost cities. Most Wizards believe that their counterparts in ancient civilizations knew secrets of magic that have been lost to the ages, and discovering those secrets could unlock the path to a power greater than any magic available in the present age.', 'Intelligence');


-- CREATE NEW TABLE FOR BACKGROUNDS (NOT IN API)

CREATE TABLE backgrounds (
    id bigserial PRIMARY KEY,
    background_name text,
    background_description text,
    background_skill_proficiency_1 text,
    background_skill_proficiency_2 text,
    background_ability_score_1 text,
    background_ability_score_2 text,
    background_ability_score_3 text,
    background_tool_proficiency text,
    background_feat text
);

INSERT INTO backgrounds (id, background_name, background_description, background_skill_proficiency_1, background_skill_proficiency_2, background_ability_score_1, background_ability_score_2, background_ability_score_3, background_tool_proficiency, background_feat)
VALUES
    (1, 'Acolyte', 'You devoted yourself to service in a temple, either nestled in a town or secluded in a sacred grove. There you performed rites in honor of a god or pantheon. You served under a priest and studied religion. Thanks to your priest’s instruction and your own devotion, you also learned how to channel a modicum of divine power in service to your place of worship and the people who prayed there.', 'Insight', 'Religion', 'Intelligence', 'Wisdom', 'Charisma', 'Calligrapher''s Supplies', 'Magic Initiate (Cleric)'),
    (2, 'Artisan', 'You began mopping floors and scrubbing counters in an artisan’s workshop for a few coppers per day as soon as you were strong enough to carry a bucket. When you were old enough to apprentice, you learned to create basic crafts of your own, as well as how to sweet-talk the occasional demanding customer. Your trade has also given you a keen eye for detail.', 'Investigation', 'Persuasion', 'Strength', 'Dexterity', 'Intelligence', 'Artisan''s Tools', 'Crafter'),
    (3, 'Charlatan', 'Once you were old enough to order an ale, you soon had a favorite stool in every tavern within ten miles of where you were born. As you traveled the circuit from public house to watering hole, you learned to prey on unfortunates who were in the market for a comforting lie or two—perhaps a sham potion or forged ancestry records.', 'Deception', 'Sleight of Hand', 'Dexterity', 'Constitution', 'Charisma', 'Forgery Kit', 'Skilled'),
    (4, 'Criminal', 'You eked out a living in dark alleyways, cutting purses or burgling shops. Perhaps you were part of a small gang of like-minded wrongdoers who looked out for each other. Or maybe you were a lone wolf, fending for yourself against the local thieves’ guild and more fearsome lawbreakers.', 'Sleight of Hand', 'Stealth', 'Dexterity', 'Constitution', 'Intelligence', 'Thieves'' Tools', 'Alert'),
    (5, 'Entertainer', 'You spent much of your youth following roving fairs and carnivals, performing odd jobs for musicians and acrobats in exchange for lessons. You may have learned how to walk a tightrope, how to play a lute in a distinct style, or how to recite poetry with impeccable diction. To this day, you thrive on applause and long for the stage.', 'Acrobatics', 'Performance', 'Strength', 'Dexterity', 'Charisma', 'Musical Instrument', 'Musician'),
    (6, 'Farmer', 'You grew up close to the land. Years tending animals and cultivating the earth rewarded you with patience and good health. You have a keen appreciation for nature’s bounty alongside a healthy respect for nature’s wrath.', 'Animal Handling', 'Nature', 'Strength', 'Constitution', 'Wisdom', 'Carpenter''s Tools', 'Tough'),
    (7, 'Guard', 'Your feet ache when you remember the countless hours you spent at your post in the tower. You were trained to keep one eye looking outside the wall, watching for marauders sweeping from the nearby forest, and your other eye looking inside the wall, searching for cutpurses and troublemakers.', 'Athletics', 'Perception', 'Strength', 'Intelligence', 'Wisdom', 'Gaming Set', 'Alert'),
    (8, 'Guide', 'You came of age outdoors, far from settled lands. Your home was anywhere you chose to spread your bedroll. There are wonders in the wilderness—strange monsters, pristine forests and streams, overgrown ruins of great halls once trod by giants—and you learned to fend for yourself as you explored them. From time to time, you guided friendly nature priests who instructed you in the fundamentals of channeling the magic of the wild.', 'Stealth', 'Survival', 'Dexterity', 'Constitution', 'Wisdom', 'Cartographer''s Tools', 'Magic Initiate (Druid)'),
    (9, 'Hermit', 'You spent your early years secluded in a hut or monastery located well beyond the outskirts of the nearest settlement. In those days, your only companions were the creatures of the forest and those who would occasionally visit to bring news of the outside world and supplies. The solitude allowed you to spend many hours pondering the mysteries of creation.', 'Medicine', 'Religion', 'Constitution', 'Wisdom', 'Charisma', 'Herbalism Kit', 'Healer'),
    (10, 'Merchant', 'You were apprenticed to a trader, caravan master, or shopkeeper, learning the fundamentals of commerce. You traveled broadly, and you earned a living by buying and selling the raw materials artisans need to practice their craft or finished works from such crafters. You might have transported goods from one place to another (by ship, wagon, or caravan) or bought them from traveling traders and sold them in your own shop.', 'Animal Handling', 'Persuasion', 'Constitution', 'Intelligence', 'Charisma', 'Navigator''s Tools', 'Lucky'),
    (11, 'Noble', 'You were raised in a castle, surrounded by wealth, power, and privilege. Your family of minor aristocrats ensured that you received a first-class education, some of which you appreciated and some of which you resented. Your time in the castle, especially the many hours you spent observing your family at court, also taught you a great deal about leadership.', 'History', 'Persuasion', 'Strength', 'Intelligence', 'Charisma', 'Gaming Set', 'Skilled'),
    (12, 'Sage', 'You spent your formative years traveling between manors and monasteries, performing various odd jobs and services in exchange for access to their libraries. You whiled away many a long evening studying books and scrolls, learning the lore of the multiverse—even the rudiments of magic—and your mind yearns for more.', 'Arcana', 'History', 'Constitution', 'Intelligence', 'Wisdom', 'Calligrapher''s Supplies', 'Magic Initiate (Wizard)'),
    (13, 'Sailor', 'You lived as a seafarer, wind at your back and decks swaying beneath your feet. You’ve perched on barstools in more ports of call than you can remember, faced mighty storms, and swapped stories with folk who live beneath the waves.', 'Acrobatics', 'Perception', 'Strength', 'Dexterity', 'Wisdom', 'Navigator''s Tools', 'Tavern Brawler'),
    (14, 'Scribe', 'You spent formative years in a scriptorium, a monastery dedicated to the preservation of knowledge, or a government agency, where you learned to write with a clear hand and produce finely written texts. Perhaps you scribed government documents or copied tomes of literature. You might have some skill as a writer of poetry, narrative, or scholarly research. Above all, you have a careful attention to detail, helping you avoid introducing mistakes to the documents you copy and create.', 'Investigation', 'Perception', 'Dexterity', 'Intelligence', 'Wisdom', 'Calligrapher''s Supplies', 'Skilled'),
    (15, 'Soldier', 'You began training for war as soon as you reached adulthood and carry precious few memories of life before you took up arms. Battle is in your blood. Sometimes you catch yourself reflexively performing the basic fighting exercises you learned first. Eventually, you put that training to use on the battlefield, protecting the realm by waging war.', 'Athletics', 'Intimidation', 'Strength', 'Dexterity', 'Constitution', 'Gaming Set', 'Savage Attacker'),
    (16, 'Wayfarer', 'You grew up on the streets surrounded by similarly ill-fated castoffs, a few of them friends and a few of them rivals. You slept where you could and did odd jobs for food. At times, when the hunger became unbearable, you resorted to theft. Still, you never lost your pride and never abandoned hope. Fate is not yet finished with you.', 'Insight', 'Stealth', 'Dexterity', 'Wisdom', 'Charisma', 'Thieves'' Tools', 'Lucky');